#!/bin/bash

yellow='\e[1;33m'
green='\e[1;32m'
red='\e[0;31m'
white='\e[1;37m'

Guided='./Guided'
Automatic='./FullAuto'

cd $HOME/temp/scripts
chmod +x *
echo -e "${green}"
echo "Welcome to Raspberry Pi Webui installer."

#Demand Root.
echo -e "${red}"
while true;do
    read -p "ARE YOU RUNNING THIS AS ROOT? NOT SUDO BUT "ROOT"(yes or no)" yn
    case $yn in
	 [Yy]* ) echo "Starting Script"; break;;
	 [Nn]* ) echo "THIS MUST RUN AS ROOT!";tput sgr0; exit;;
	 * ) echo "Please answer yes or no."; exit;;
 esac
done
clear
echo -e "${green}"
echo "1.Guided Install"
echo "2.Automatic Installer"

#Display install Options
echo -e "${yellow}"
while true;do
    read -p "Please select your install method: " abe
    case $abe in
         [1] ) "${Guided}"; tput sgr0; break;;
         [2] ) "${Automatic}"; tput sgr0; break;;
         [EeQq]* ) echo "Thank You For Trying this out!!"; tput sgr0; exit;;
         * ) echo -e "${red}"; echo "Please Select one of the options or Exit to quit"; echo -e "${yellow}";;
 esac
done
