#!/bin/bash

yellow='\e[1;33m'
green='\e[1;32m'
red='\e[0;31m'
white='\e[1;37m'

Guided='./Guided'
Automatic='./FullAuto'

cd scripts
chmod +x *
echo -e "${green}"
echo "Welcome to Raspberry Pi Webui installer."

#Demand Root.
FILE="/tmp/out.$$"
GREP="/bin/grep"
#....
# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root, use sudo ./Autoinstallwebui"; tput sgr0 1>&2
   exit 1
fi
# ...
clear
echo -e "${green}"
echo "1.Guided Install"
echo "2.Automatic Installer"

#Display install Options
echo -e "${yellow}"
while true;do
    read -p "Please select your install method Exit to quit: " abe
    case $abe in
         [1] ) clear; "${Guided}"; tput sgr0; break;;
         [2] ) clear; "${Automatic}"; tput sgr0; break;;
         [EeQq]* ) echo "Thank You For Trying this out!!"; tput sgr0; exit;;
         * ) echo -e "${red}"; echo "Please Select one of the options or Exit to quit"; echo -e "${yellow}";;
 esac
done
